---
- name: create ticket with notes
  hosts: 192.168.161.9
  gather_facts: no
  connection: network_cli

  tasks:
  - name: include vars
    include_vars: incident_vars.yml

  - name: Create an incident
    snow_record:
      state: present
      table: incident
      data:
        severity: "{{ severity}}"
        priority: "{{ priority}}"
        short_description: "This ticket was created by Zabbix"
    register: new_incident
    delegate_to: 127.0.0.1

  - debug: var=new_incident.record
